# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/templates/window_texteditor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 219)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radio_plain = QtWidgets.QRadioButton(Dialog)
        self.radio_plain.setChecked(True)
        self.radio_plain.setObjectName("radio_plain")
        self.horizontalLayout_2.addWidget(self.radio_plain)
        self.radio_html = QtWidgets.QRadioButton(Dialog)
        self.radio_html.setObjectName("radio_html")
        self.horizontalLayout_2.addWidget(self.radio_html)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_colour = QtWidgets.QPushButton(Dialog)
        self.button_colour.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_colour.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logos/logo_font_colour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_colour.setIcon(icon)
        self.button_colour.setObjectName("button_colour")
        self.horizontalLayout.addWidget(self.button_colour)
        self.button_bold = QtWidgets.QPushButton(Dialog)
        self.button_bold.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_bold.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../logos/logo_font_bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bold.setIcon(icon1)
        self.button_bold.setObjectName("button_bold")
        self.horizontalLayout.addWidget(self.button_bold)
        self.button_italic = QtWidgets.QPushButton(Dialog)
        self.button_italic.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_italic.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../logos/logo_font_italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_italic.setIcon(icon2)
        self.button_italic.setObjectName("button_italic")
        self.horizontalLayout.addWidget(self.button_italic)
        self.button_underline = QtWidgets.QPushButton(Dialog)
        self.button_underline.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_underline.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../logos/logo_font_underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_underline.setIcon(icon3)
        self.button_underline.setObjectName("button_underline")
        self.horizontalLayout.addWidget(self.button_underline)
        self.button_align_left = QtWidgets.QPushButton(Dialog)
        self.button_align_left.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_align_left.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../logos/logo_font_align_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_align_left.setIcon(icon4)
        self.button_align_left.setObjectName("button_align_left")
        self.horizontalLayout.addWidget(self.button_align_left)
        self.button_align_center = QtWidgets.QPushButton(Dialog)
        self.button_align_center.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_align_center.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../logos/logo_font_align_center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_align_center.setIcon(icon5)
        self.button_align_center.setObjectName("button_align_center")
        self.horizontalLayout.addWidget(self.button_align_center)
        self.button_align_right = QtWidgets.QPushButton(Dialog)
        self.button_align_right.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_align_right.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../logos/logo_font_align_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_align_right.setIcon(icon6)
        self.button_align_right.setObjectName("button_align_right")
        self.horizontalLayout.addWidget(self.button_align_right)
        self.button_align_justify = QtWidgets.QPushButton(Dialog)
        self.button_align_justify.setMaximumSize(QtCore.QSize(48, 16777215))
        self.button_align_justify.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../logos/logo_font_align_justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_align_justify.setIcon(icon7)
        self.button_align_justify.setObjectName("button_align_justify")
        self.horizontalLayout.addWidget(self.button_align_justify)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.edit_text = QtWidgets.QTextEdit(Dialog)
        self.edit_text.setObjectName("edit_text")
        self.verticalLayout.addWidget(self.edit_text)
        self.widget_warning = QtWidgets.QWidget(Dialog)
        self.widget_warning.setObjectName("widget_warning")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_warning)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_warning = QtWidgets.QLabel(self.widget_warning)
        self.label_warning.setMaximumSize(QtCore.QSize(20, 20))
        self.label_warning.setText("")
        self.label_warning.setPixmap(QtGui.QPixmap("../logos/logo_danger.png"))
        self.label_warning.setScaledContents(True)
        self.label_warning.setObjectName("label_warning")
        self.horizontalLayout_3.addWidget(self.label_warning)
        self.label_2 = QtWidgets.QLabel(self.widget_warning)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_warning)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Text Editor"))
        self.label.setText(_translate("Dialog", "Output:"))
        self.radio_plain.setText(_translate("Dialog", "To Plain Text"))
        self.radio_html.setText(_translate("Dialog", "To HTML"))
        self.label_2.setText(_translate("Dialog", "This may not work in all mod managers."))

