# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/templates/preview_mo.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 581)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.button_preview_more = QtWidgets.QPushButton(Form)
        self.button_preview_more.setMaximumSize(QtCore.QSize(24, 16777215))
        self.button_preview_more.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logos/logo_more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_preview_more.setIcon(icon)
        self.button_preview_more.setFlat(True)
        self.button_preview_more.setObjectName("button_preview_more")
        self.horizontalLayout_2.addWidget(self.button_preview_more)
        self.button_preview_less = QtWidgets.QPushButton(Form)
        self.button_preview_less.setMaximumSize(QtCore.QSize(24, 16777215))
        self.button_preview_less.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../logos/logo_less.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_preview_less.setIcon(icon1)
        self.button_preview_less.setFlat(True)
        self.button_preview_less.setObjectName("button_preview_less")
        self.horizontalLayout_2.addWidget(self.button_preview_less)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget_preview = QtWidgets.QWidget(Form)
        self.widget_preview.setObjectName("widget_preview")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_preview)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget_preview)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_name = QtWidgets.QLabel(self.widget_preview)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_name)
        self.label_3 = QtWidgets.QLabel(self.widget_preview)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_author = QtWidgets.QLabel(self.widget_preview)
        self.label_author.setText("")
        self.label_author.setObjectName("label_author")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_author)
        self.label_5 = QtWidgets.QLabel(self.widget_preview)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_version = QtWidgets.QLabel(self.widget_preview)
        self.label_version.setText("")
        self.label_version.setObjectName("label_version")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_version)
        self.label_7 = QtWidgets.QLabel(self.widget_preview)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_website = QtWidgets.QLabel(self.widget_preview)
        self.label_website.setText("")
        self.label_website.setObjectName("label_website")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_website)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.widget_preview)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_label = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_label.setOrientation(QtCore.Qt.Vertical)
        self.splitter_label.setChildrenCollapsible(False)
        self.splitter_label.setObjectName("splitter_label")
        self.label_description = QtWidgets.QTextBrowser(self.splitter_label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_description.sizePolicy().hasHeightForWidth())
        self.label_description.setSizePolicy(sizePolicy)
        self.label_description.setObjectName("label_description")
        self.widget_base = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_base.sizePolicy().hasHeightForWidth())
        self.widget_base.setSizePolicy(sizePolicy)
        self.widget_base.setObjectName("widget_base")
        self.layout_widget = QtWidgets.QVBoxLayout(self.widget_base)
        self.layout_widget.setContentsMargins(0, 0, 0, 0)
        self.layout_widget.setSpacing(3)
        self.layout_widget.setObjectName("layout_widget")
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.verticalLayout.addWidget(self.widget_preview)
        self.line = QtWidgets.QFrame(Form)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.button_results_more = QtWidgets.QPushButton(Form)
        self.button_results_more.setMaximumSize(QtCore.QSize(24, 16777215))
        self.button_results_more.setText("")
        self.button_results_more.setIcon(icon)
        self.button_results_more.setFlat(True)
        self.button_results_more.setObjectName("button_results_more")
        self.horizontalLayout.addWidget(self.button_results_more)
        self.button_results_less = QtWidgets.QPushButton(Form)
        self.button_results_less.setMaximumSize(QtCore.QSize(24, 16777215))
        self.button_results_less.setText("")
        self.button_results_less.setIcon(icon1)
        self.button_results_less.setFlat(True)
        self.button_results_less.setObjectName("button_results_less")
        self.horizontalLayout.addWidget(self.button_results_less)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_results = QtWidgets.QWidget(Form)
        self.widget_results.setObjectName("widget_results")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_results)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tree_results = QtWidgets.QTreeView(self.widget_results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_results.sizePolicy().hasHeightForWidth())
        self.tree_results.setSizePolicy(sizePolicy)
        self.tree_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tree_results.setIndentation(10)
        self.tree_results.setUniformRowHeights(True)
        self.tree_results.setObjectName("tree_results")
        self.tree_results.header().setCascadingSectionResizes(False)
        self.tree_results.header().setDefaultSectionSize(150)
        self.tree_results.header().setMinimumSectionSize(100)
        self.verticalLayout_2.addWidget(self.tree_results)
        self.label_6 = QtWidgets.QLabel(self.widget_results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.list_flags = QtWidgets.QTreeView(self.widget_results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_flags.sizePolicy().hasHeightForWidth())
        self.list_flags.setSizePolicy(sizePolicy)
        self.list_flags.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_flags.setObjectName("list_flags")
        self.verticalLayout_2.addWidget(self.list_flags)
        self.verticalLayout.addWidget(self.widget_results)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.button_full_preview = QtWidgets.QPushButton(Form)
        self.button_full_preview.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_full_preview.sizePolicy().hasHeightForWidth())
        self.button_full_preview.setSizePolicy(sizePolicy)
        self.button_full_preview.setObjectName("button_full_preview")
        self.verticalLayout.addWidget(self.button_full_preview, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Step Preview"))
        self.label.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Author"))
        self.label_5.setText(_translate("Form", "Version"))
        self.label_7.setText(_translate("Form", "Website"))
        self.label_4.setText(_translate("Form", "Page Results"))
        self.label_2.setText(_translate("Form", "Files Installed"))
        self.label_6.setText(_translate("Form", "Flags Set"))
        self.button_full_preview.setText(_translate("Form", "Start Full Preview"))

