# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/templates/settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(565, 317)
        Dialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setModal(False)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.check_intro = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_intro.setObjectName("check_intro")
        self.horizontalLayout_7.addWidget(self.check_intro)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.check_advanced = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_advanced.setEnabled(False)
        self.check_advanced.setObjectName("check_advanced")
        self.horizontalLayout_8.addWidget(self.check_advanced)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.combo_code_refresh = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_code_refresh.setObjectName("combo_code_refresh")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.horizontalLayout_6.addWidget(self.combo_code_refresh)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.check_installSteps = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_installSteps.setChecked(True)
        self.check_installSteps.setObjectName("check_installSteps")
        self.horizontalLayout_10.addWidget(self.check_installSteps)
        self.combo_installSteps = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_installSteps.setObjectName("combo_installSteps")
        self.combo_installSteps.addItem("")
        self.combo_installSteps.addItem("")
        self.combo_installSteps.addItem("")
        self.horizontalLayout_10.addWidget(self.combo_installSteps)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.check_optionalFileGroups = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_optionalFileGroups.setChecked(True)
        self.check_optionalFileGroups.setObjectName("check_optionalFileGroups")
        self.horizontalLayout_11.addWidget(self.check_optionalFileGroups)
        self.combo_optionalFileGroups = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_optionalFileGroups.setObjectName("combo_optionalFileGroups")
        self.combo_optionalFileGroups.addItem("")
        self.combo_optionalFileGroups.addItem("")
        self.combo_optionalFileGroups.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_optionalFileGroups)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.check_type = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_type.setChecked(True)
        self.check_type.setObjectName("check_type")
        self.horizontalLayout_12.addWidget(self.check_type)
        self.combo_type = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_type)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_defaultType = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_defaultType.setChecked(True)
        self.check_defaultType.setObjectName("check_defaultType")
        self.horizontalLayout_13.addWidget(self.check_defaultType)
        self.combo_defaultType = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_defaultType.setObjectName("combo_defaultType")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.horizontalLayout_13.addWidget(self.combo_defaultType)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_valid_load = QtWidgets.QCheckBox(self.groupBox)
        self.check_valid_load.setChecked(True)
        self.check_valid_load.setObjectName("check_valid_load")
        self.verticalLayout.addWidget(self.check_valid_load)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.check_valid_load_ignore = QtWidgets.QCheckBox(self.groupBox)
        self.check_valid_load_ignore.setEnabled(True)
        self.check_valid_load_ignore.setObjectName("check_valid_load_ignore")
        self.horizontalLayout_5.addWidget(self.check_valid_load_ignore)
        self.horizontalLayout_5.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_warn_load = QtWidgets.QCheckBox(self.groupBox)
        self.check_warn_load.setChecked(True)
        self.check_warn_load.setObjectName("check_warn_load")
        self.verticalLayout_2.addWidget(self.check_warn_load)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.check_warn_load_ignore = QtWidgets.QCheckBox(self.groupBox)
        self.check_warn_load_ignore.setEnabled(True)
        self.check_warn_load_ignore.setObjectName("check_warn_load_ignore")
        self.horizontalLayout_4.addWidget(self.check_warn_load_ignore)
        self.horizontalLayout_4.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.check_valid_save = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_valid_save.sizePolicy().hasHeightForWidth())
        self.check_valid_save.setSizePolicy(sizePolicy)
        self.check_valid_save.setChecked(True)
        self.check_valid_save.setObjectName("check_valid_save")
        self.verticalLayout_4.addWidget(self.check_valid_save)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.check_valid_save_ignore = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_valid_save_ignore.sizePolicy().hasHeightForWidth())
        self.check_valid_save_ignore.setSizePolicy(sizePolicy)
        self.check_valid_save_ignore.setObjectName("check_valid_save_ignore")
        self.horizontalLayout_3.addWidget(self.check_valid_save_ignore)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.check_warn_save = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_warn_save.setChecked(True)
        self.check_warn_save.setObjectName("check_warn_save")
        self.verticalLayout_3.addWidget(self.check_warn_save)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.check_warn_save_ignore = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_warn_save_ignore.setEnabled(True)
        self.check_warn_save_ignore.setObjectName("check_warn_save_ignore")
        self.horizontalLayout_2.addWidget(self.check_warn_save_ignore)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.groupBox_3.setTitle(_translate("Dialog", "General"))
        self.check_intro.setText(_translate("Dialog", "Show intro window at statup."))
        self.check_advanced.setText(_translate("Dialog", "Show the Advanced View at startup."))
        self.label.setText(_translate("Dialog", "Preview Refresh Rate"))
        self.combo_code_refresh.setItemText(0, _translate("Dialog", "Never"))
        self.combo_code_refresh.setItemText(1, _translate("Dialog", "On Refresh"))
        self.combo_code_refresh.setItemText(2, _translate("Dialog", "On Node Select"))
        self.combo_code_refresh.setItemText(3, _translate("Dialog", "On Property Editing"))
        self.groupBox_4.setTitle(_translate("Dialog", "Defaults"))
        self.check_installSteps.setText(_translate("Dialog", "Installation Steps"))
        self.combo_installSteps.setItemText(0, _translate("Dialog", "Explicit"))
        self.combo_installSteps.setItemText(1, _translate("Dialog", "Ascending"))
        self.combo_installSteps.setItemText(2, _translate("Dialog", "Descending"))
        self.check_optionalFileGroups.setText(_translate("Dialog", "Option Group"))
        self.combo_optionalFileGroups.setItemText(0, _translate("Dialog", "Explicit"))
        self.combo_optionalFileGroups.setItemText(1, _translate("Dialog", "Ascending"))
        self.combo_optionalFileGroups.setItemText(2, _translate("Dialog", "Descending"))
        self.check_type.setText(_translate("Dialog", "Type"))
        self.combo_type.setItemText(0, _translate("Dialog", "Optional"))
        self.combo_type.setItemText(1, _translate("Dialog", "Required"))
        self.combo_type.setItemText(2, _translate("Dialog", "Recommended"))
        self.combo_type.setItemText(3, _translate("Dialog", "CouldBeUsable"))
        self.combo_type.setItemText(4, _translate("Dialog", "NotUsable"))
        self.check_defaultType.setText(_translate("Dialog", "Default Type"))
        self.combo_defaultType.setItemText(0, _translate("Dialog", "Optional"))
        self.combo_defaultType.setItemText(1, _translate("Dialog", "Required"))
        self.combo_defaultType.setItemText(2, _translate("Dialog", "Recommended"))
        self.combo_defaultType.setItemText(3, _translate("Dialog", "CouldBeUsable"))
        self.combo_defaultType.setItemText(4, _translate("Dialog", "NotUsable"))
        self.groupBox.setTitle(_translate("Dialog", "At Loading"))
        self.check_valid_load.setText(_translate("Dialog", "Validate installer."))
        self.check_valid_load_ignore.setText(_translate("Dialog", "Ignore errors and continue loading."))
        self.check_warn_load.setText(_translate("Dialog", "Check installer for common errors."))
        self.check_warn_load_ignore.setText(_translate("Dialog", "Ignore errors and continue loading."))
        self.groupBox_2.setTitle(_translate("Dialog", "At Saving"))
        self.check_valid_save.setText(_translate("Dialog", "Validate installer."))
        self.check_valid_save_ignore.setText(_translate("Dialog", "Ignore errors and continue saving."))
        self.check_warn_save.setText(_translate("Dialog", "Check installer for common errors."))
        self.check_warn_save_ignore.setText(_translate("Dialog", "Ignore errors and continue saving."))

