# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/templates/window_settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(565, 396)
        Dialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setModal(False)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_intro = QtWidgets.QCheckBox(self.tab)
        self.check_intro.setObjectName("check_intro")
        self.verticalLayout_7.addWidget(self.check_intro)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.check_advanced = QtWidgets.QCheckBox(self.tab)
        self.check_advanced.setEnabled(False)
        self.check_advanced.setObjectName("check_advanced")
        self.verticalLayout_7.addWidget(self.check_advanced)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.combo_code_refresh = QtWidgets.QComboBox(self.tab)
        self.combo_code_refresh.setObjectName("combo_code_refresh")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.combo_code_refresh.addItem("")
        self.horizontalLayout_6.addWidget(self.combo_code_refresh)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.check_intro.raise_()
        self.check_advanced.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.button_colour_required = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_required.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_colour_required.setText("")
        self.button_colour_required.setObjectName("button_colour_required")
        self.horizontalLayout_7.addWidget(self.button_colour_required)
        self.button_colour_reset_required = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_reset_required.setObjectName("button_colour_reset_required")
        self.horizontalLayout_7.addWidget(self.button_colour_reset_required)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.button_colour_atleastone = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_atleastone.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_colour_atleastone.setText("")
        self.button_colour_atleastone.setObjectName("button_colour_atleastone")
        self.horizontalLayout_8.addWidget(self.button_colour_atleastone)
        self.button_colour_reset_atleastone = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_reset_atleastone.setObjectName("button_colour_reset_atleastone")
        self.horizontalLayout_8.addWidget(self.button_colour_reset_atleastone)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.button_colour_either = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_either.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_colour_either.setText("")
        self.button_colour_either.setObjectName("button_colour_either")
        self.horizontalLayout_9.addWidget(self.button_colour_either)
        self.button_colour_reset_either = QtWidgets.QPushButton(self.tab_5)
        self.button_colour_reset_either.setObjectName("button_colour_reset_either")
        self.horizontalLayout_9.addWidget(self.button_colour_reset_either)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.line_9 = QtWidgets.QFrame(self.tab_5)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setMidLineWidth(0)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.combo_style = QtWidgets.QComboBox(self.tab_5)
        self.combo_style.setObjectName("combo_style")
        self.combo_style.addItem("")
        self.combo_style.addItem("")
        self.combo_style.addItem("")
        self.horizontalLayout_14.addWidget(self.combo_style)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.widget_warning_style = QtWidgets.QWidget(self.tab_5)
        self.widget_warning_style.setObjectName("widget_warning_style")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_warning_style)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.label_warning_style = QtWidgets.QLabel(self.widget_warning_style)
        self.label_warning_style.setMaximumSize(QtCore.QSize(20, 20))
        self.label_warning_style.setText("")
        self.label_warning_style.setPixmap(QtGui.QPixmap("../logos/logo_danger.png"))
        self.label_warning_style.setScaledContents(True)
        self.label_warning_style.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_warning_style.setWordWrap(False)
        self.label_warning_style.setObjectName("label_warning_style")
        self.horizontalLayout_16.addWidget(self.label_warning_style)
        self.label_13 = QtWidgets.QLabel(self.widget_warning_style)
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout_10.addWidget(self.widget_warning_style)
        self.line_15 = QtWidgets.QFrame(self.tab_5)
        self.line_15.setMidLineWidth(0)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_10.addWidget(self.line_15)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.combo_palette = QtWidgets.QComboBox(self.tab_5)
        self.combo_palette.setObjectName("combo_palette")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.combo_palette.addItem("")
        self.horizontalLayout_15.addWidget(self.combo_palette)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.widget_warning_palette = QtWidgets.QWidget(self.tab_5)
        self.widget_warning_palette.setObjectName("widget_warning_palette")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_warning_palette)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.label_warning_palette = QtWidgets.QLabel(self.widget_warning_palette)
        self.label_warning_palette.setMaximumSize(QtCore.QSize(20, 20))
        self.label_warning_palette.setText("")
        self.label_warning_palette.setPixmap(QtGui.QPixmap("../logos/logo_danger.png"))
        self.label_warning_palette.setScaledContents(True)
        self.label_warning_palette.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_warning_palette.setWordWrap(False)
        self.label_warning_palette.setObjectName("label_warning_palette")
        self.horizontalLayout_17.addWidget(self.label_warning_palette)
        self.label_15 = QtWidgets.QLabel(self.widget_warning_palette)
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_10.addWidget(self.widget_warning_palette)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_valid_load = QtWidgets.QCheckBox(self.tab_3)
        self.check_valid_load.setChecked(True)
        self.check_valid_load.setObjectName("check_valid_load")
        self.verticalLayout.addWidget(self.check_valid_load)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.check_valid_load_ignore = QtWidgets.QCheckBox(self.tab_3)
        self.check_valid_load_ignore.setEnabled(True)
        self.check_valid_load_ignore.setObjectName("check_valid_load_ignore")
        self.horizontalLayout_5.addWidget(self.check_valid_load_ignore)
        self.horizontalLayout_5.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.line_7 = QtWidgets.QFrame(self.tab_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_6.addWidget(self.line_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_warn_load = QtWidgets.QCheckBox(self.tab_3)
        self.check_warn_load.setChecked(True)
        self.check_warn_load.setObjectName("check_warn_load")
        self.verticalLayout_2.addWidget(self.check_warn_load)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.check_warn_load_ignore = QtWidgets.QCheckBox(self.tab_3)
        self.check_warn_load_ignore.setEnabled(True)
        self.check_warn_load_ignore.setObjectName("check_warn_load_ignore")
        self.horizontalLayout_4.addWidget(self.check_warn_load_ignore)
        self.horizontalLayout_4.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.check_valid_save = QtWidgets.QCheckBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_valid_save.sizePolicy().hasHeightForWidth())
        self.check_valid_save.setSizePolicy(sizePolicy)
        self.check_valid_save.setChecked(True)
        self.check_valid_save.setObjectName("check_valid_save")
        self.verticalLayout_4.addWidget(self.check_valid_save)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.check_valid_save_ignore = QtWidgets.QCheckBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_valid_save_ignore.sizePolicy().hasHeightForWidth())
        self.check_valid_save_ignore.setSizePolicy(sizePolicy)
        self.check_valid_save_ignore.setObjectName("check_valid_save_ignore")
        self.horizontalLayout_3.addWidget(self.check_valid_save_ignore)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.line_8 = QtWidgets.QFrame(self.tab_4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_5.addWidget(self.line_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.check_warn_save = QtWidgets.QCheckBox(self.tab_4)
        self.check_warn_save.setChecked(True)
        self.check_warn_save.setObjectName("check_warn_save")
        self.verticalLayout_3.addWidget(self.check_warn_save)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.check_warn_save_ignore = QtWidgets.QCheckBox(self.tab_4)
        self.check_warn_save_ignore.setEnabled(True)
        self.check_warn_save_ignore.setObjectName("check_warn_save_ignore")
        self.horizontalLayout_2.addWidget(self.check_warn_save_ignore)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.check_installSteps = QtWidgets.QCheckBox(self.tab_2)
        self.check_installSteps.setChecked(True)
        self.check_installSteps.setObjectName("check_installSteps")
        self.horizontalLayout_10.addWidget(self.check_installSteps)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.combo_installSteps = QtWidgets.QComboBox(self.tab_2)
        self.combo_installSteps.setObjectName("combo_installSteps")
        self.combo_installSteps.addItem("")
        self.combo_installSteps.addItem("")
        self.combo_installSteps.addItem("")
        self.horizontalLayout_10.addWidget(self.combo_installSteps)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.check_optionalFileGroups = QtWidgets.QCheckBox(self.tab_2)
        self.check_optionalFileGroups.setChecked(True)
        self.check_optionalFileGroups.setObjectName("check_optionalFileGroups")
        self.horizontalLayout_11.addWidget(self.check_optionalFileGroups)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.combo_optionalFileGroups = QtWidgets.QComboBox(self.tab_2)
        self.combo_optionalFileGroups.setObjectName("combo_optionalFileGroups")
        self.combo_optionalFileGroups.addItem("")
        self.combo_optionalFileGroups.addItem("")
        self.combo_optionalFileGroups.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_optionalFileGroups)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_9.addWidget(self.line_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.check_type = QtWidgets.QCheckBox(self.tab_2)
        self.check_type.setChecked(True)
        self.check_type.setObjectName("check_type")
        self.horizontalLayout_12.addWidget(self.check_type)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.combo_type = QtWidgets.QComboBox(self.tab_2)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_type)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_9.addWidget(self.line_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_defaultType = QtWidgets.QCheckBox(self.tab_2)
        self.check_defaultType.setChecked(True)
        self.check_defaultType.setObjectName("check_defaultType")
        self.horizontalLayout_13.addWidget(self.check_defaultType)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.combo_defaultType = QtWidgets.QComboBox(self.tab_2)
        self.combo_defaultType.setObjectName("combo_defaultType")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.combo_defaultType.addItem("")
        self.horizontalLayout_13.addWidget(self.combo_defaultType)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.check_intro.setText(_translate("Dialog", "Show intro window at statup."))
        self.check_advanced.setText(_translate("Dialog", "Show the Advanced View at startup."))
        self.label.setText(_translate("Dialog", "Preview Refresh Rate"))
        self.combo_code_refresh.setItemText(0, _translate("Dialog", "Never"))
        self.combo_code_refresh.setItemText(1, _translate("Dialog", "On Refresh"))
        self.combo_code_refresh.setItemText(2, _translate("Dialog", "On Node Select"))
        self.combo_code_refresh.setItemText(3, _translate("Dialog", "On Property Editing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "General"))
        self.label_9.setText(_translate("Dialog", "Special Button Colours"))
        self.label_10.setText(_translate("Dialog", "Required"))
        self.button_colour_reset_required.setText(_translate("Dialog", "Reset to Default"))
        self.label_11.setText(_translate("Dialog", "At Least One"))
        self.button_colour_reset_atleastone.setText(_translate("Dialog", "Reset to Default"))
        self.label_12.setText(_translate("Dialog", "Either"))
        self.button_colour_reset_either.setText(_translate("Dialog", "Reset to Default"))
        self.label_14.setText(_translate("Dialog", "Style"))
        self.combo_style.setItemText(0, _translate("Dialog", "Default"))
        self.combo_style.setItemText(1, _translate("Dialog", "Windows"))
        self.combo_style.setItemText(2, _translate("Dialog", "Fusion"))
        self.label_13.setText(_translate("Dialog", "This setting requires a restart to take effect."))
        self.label_16.setText(_translate("Dialog", "Palette"))
        self.combo_palette.setItemText(0, _translate("Dialog", "Default"))
        self.combo_palette.setItemText(1, _translate("Dialog", "aliceblue"))
        self.combo_palette.setItemText(2, _translate("Dialog", "antiquewhite"))
        self.combo_palette.setItemText(3, _translate("Dialog", "aqua"))
        self.combo_palette.setItemText(4, _translate("Dialog", "aquamarine"))
        self.combo_palette.setItemText(5, _translate("Dialog", "azure"))
        self.combo_palette.setItemText(6, _translate("Dialog", "beige"))
        self.combo_palette.setItemText(7, _translate("Dialog", "bisque"))
        self.combo_palette.setItemText(8, _translate("Dialog", "black"))
        self.combo_palette.setItemText(9, _translate("Dialog", "blanchedalmond"))
        self.combo_palette.setItemText(10, _translate("Dialog", "blue"))
        self.combo_palette.setItemText(11, _translate("Dialog", "blueviolet"))
        self.combo_palette.setItemText(12, _translate("Dialog", "brown"))
        self.combo_palette.setItemText(13, _translate("Dialog", "burlywood"))
        self.combo_palette.setItemText(14, _translate("Dialog", "cadetblue"))
        self.combo_palette.setItemText(15, _translate("Dialog", "chartreuse"))
        self.combo_palette.setItemText(16, _translate("Dialog", "chocolate"))
        self.combo_palette.setItemText(17, _translate("Dialog", "coral"))
        self.combo_palette.setItemText(18, _translate("Dialog", "cornflowerblue"))
        self.combo_palette.setItemText(19, _translate("Dialog", "cornsilk"))
        self.combo_palette.setItemText(20, _translate("Dialog", "crimson"))
        self.combo_palette.setItemText(21, _translate("Dialog", "cyan"))
        self.combo_palette.setItemText(22, _translate("Dialog", "darkblue"))
        self.combo_palette.setItemText(23, _translate("Dialog", "darkcyan"))
        self.combo_palette.setItemText(24, _translate("Dialog", "darkgoldenrod"))
        self.combo_palette.setItemText(25, _translate("Dialog", "darkgray"))
        self.combo_palette.setItemText(26, _translate("Dialog", "darkgreen"))
        self.combo_palette.setItemText(27, _translate("Dialog", "darkgrey"))
        self.combo_palette.setItemText(28, _translate("Dialog", "darkkhaki"))
        self.combo_palette.setItemText(29, _translate("Dialog", "darkmagenta"))
        self.combo_palette.setItemText(30, _translate("Dialog", "darkolivegreen"))
        self.combo_palette.setItemText(31, _translate("Dialog", "darkorange"))
        self.combo_palette.setItemText(32, _translate("Dialog", "darkorchid"))
        self.combo_palette.setItemText(33, _translate("Dialog", "darkred"))
        self.combo_palette.setItemText(34, _translate("Dialog", "darksalmon"))
        self.combo_palette.setItemText(35, _translate("Dialog", "darkseagreen"))
        self.combo_palette.setItemText(36, _translate("Dialog", "darkslateblue"))
        self.combo_palette.setItemText(37, _translate("Dialog", "darkslategray"))
        self.combo_palette.setItemText(38, _translate("Dialog", "darkturquoise"))
        self.combo_palette.setItemText(39, _translate("Dialog", "darkviolet"))
        self.combo_palette.setItemText(40, _translate("Dialog", "deeppink"))
        self.combo_palette.setItemText(41, _translate("Dialog", "deepskyblue"))
        self.combo_palette.setItemText(42, _translate("Dialog", "dimgray"))
        self.combo_palette.setItemText(43, _translate("Dialog", "dodgerblue"))
        self.combo_palette.setItemText(44, _translate("Dialog", "firebrick"))
        self.combo_palette.setItemText(45, _translate("Dialog", "floralwhite"))
        self.combo_palette.setItemText(46, _translate("Dialog", "forestgreen"))
        self.combo_palette.setItemText(47, _translate("Dialog", "fuchsia"))
        self.combo_palette.setItemText(48, _translate("Dialog", "gainsboro"))
        self.combo_palette.setItemText(49, _translate("Dialog", "ghostwhite"))
        self.combo_palette.setItemText(50, _translate("Dialog", "gold"))
        self.combo_palette.setItemText(51, _translate("Dialog", "goldenrod"))
        self.combo_palette.setItemText(52, _translate("Dialog", "gray"))
        self.combo_palette.setItemText(53, _translate("Dialog", "green"))
        self.combo_palette.setItemText(54, _translate("Dialog", "greenyellow"))
        self.combo_palette.setItemText(55, _translate("Dialog", "honeydew"))
        self.combo_palette.setItemText(56, _translate("Dialog", "hotpink"))
        self.combo_palette.setItemText(57, _translate("Dialog", "indianred"))
        self.combo_palette.setItemText(58, _translate("Dialog", "indigo"))
        self.combo_palette.setItemText(59, _translate("Dialog", "ivory"))
        self.combo_palette.setItemText(60, _translate("Dialog", "khaki"))
        self.combo_palette.setItemText(61, _translate("Dialog", "lavender"))
        self.combo_palette.setItemText(62, _translate("Dialog", "lavenderblush"))
        self.combo_palette.setItemText(63, _translate("Dialog", "lawngreen"))
        self.combo_palette.setItemText(64, _translate("Dialog", "lemonchiffon"))
        self.combo_palette.setItemText(65, _translate("Dialog", "lightblue"))
        self.combo_palette.setItemText(66, _translate("Dialog", "lightcoral"))
        self.combo_palette.setItemText(67, _translate("Dialog", "lightcyan"))
        self.combo_palette.setItemText(68, _translate("Dialog", "lightgoldenrodyellow"))
        self.combo_palette.setItemText(69, _translate("Dialog", "lightgray"))
        self.combo_palette.setItemText(70, _translate("Dialog", "lightgreen"))
        self.combo_palette.setItemText(71, _translate("Dialog", "lightpink"))
        self.combo_palette.setItemText(72, _translate("Dialog", "lightsalmon"))
        self.combo_palette.setItemText(73, _translate("Dialog", "lightseagreen"))
        self.combo_palette.setItemText(74, _translate("Dialog", "lightskyblue"))
        self.combo_palette.setItemText(75, _translate("Dialog", "lightslategray"))
        self.combo_palette.setItemText(76, _translate("Dialog", "lightsteelblue"))
        self.combo_palette.setItemText(77, _translate("Dialog", "lightyellow"))
        self.combo_palette.setItemText(78, _translate("Dialog", "lime"))
        self.combo_palette.setItemText(79, _translate("Dialog", "limegreen"))
        self.combo_palette.setItemText(80, _translate("Dialog", "linen"))
        self.combo_palette.setItemText(81, _translate("Dialog", "magenta"))
        self.combo_palette.setItemText(82, _translate("Dialog", "maroon"))
        self.combo_palette.setItemText(83, _translate("Dialog", "mediumaquamarine"))
        self.combo_palette.setItemText(84, _translate("Dialog", "mediumblue"))
        self.combo_palette.setItemText(85, _translate("Dialog", "mediumorchid"))
        self.combo_palette.setItemText(86, _translate("Dialog", "mediumpurple"))
        self.combo_palette.setItemText(87, _translate("Dialog", "mediumseagreen"))
        self.combo_palette.setItemText(88, _translate("Dialog", "mediumslateblue"))
        self.combo_palette.setItemText(89, _translate("Dialog", "mediumspringgreen"))
        self.combo_palette.setItemText(90, _translate("Dialog", "mediumturquoise"))
        self.combo_palette.setItemText(91, _translate("Dialog", "mediumvioletred"))
        self.combo_palette.setItemText(92, _translate("Dialog", "midnightblue"))
        self.combo_palette.setItemText(93, _translate("Dialog", "mintcream"))
        self.combo_palette.setItemText(94, _translate("Dialog", "mistyrose"))
        self.combo_palette.setItemText(95, _translate("Dialog", "moccasin"))
        self.combo_palette.setItemText(96, _translate("Dialog", "navajowhite"))
        self.combo_palette.setItemText(97, _translate("Dialog", "navy"))
        self.combo_palette.setItemText(98, _translate("Dialog", "oldlace"))
        self.combo_palette.setItemText(99, _translate("Dialog", "olive"))
        self.combo_palette.setItemText(100, _translate("Dialog", "olivedrab"))
        self.combo_palette.setItemText(101, _translate("Dialog", "orange"))
        self.combo_palette.setItemText(102, _translate("Dialog", "orangered"))
        self.combo_palette.setItemText(103, _translate("Dialog", "orchid"))
        self.combo_palette.setItemText(104, _translate("Dialog", "palegoldenrod"))
        self.combo_palette.setItemText(105, _translate("Dialog", "palegreen"))
        self.combo_palette.setItemText(106, _translate("Dialog", "paleturquoise"))
        self.combo_palette.setItemText(107, _translate("Dialog", "palevioletred"))
        self.combo_palette.setItemText(108, _translate("Dialog", "papayawhip"))
        self.combo_palette.setItemText(109, _translate("Dialog", "peachpuff"))
        self.combo_palette.setItemText(110, _translate("Dialog", "peru"))
        self.combo_palette.setItemText(111, _translate("Dialog", "pink"))
        self.combo_palette.setItemText(112, _translate("Dialog", "plum"))
        self.combo_palette.setItemText(113, _translate("Dialog", "powderblue"))
        self.combo_palette.setItemText(114, _translate("Dialog", "purple"))
        self.combo_palette.setItemText(115, _translate("Dialog", "red"))
        self.combo_palette.setItemText(116, _translate("Dialog", "rosybrown"))
        self.combo_palette.setItemText(117, _translate("Dialog", "royalblue"))
        self.combo_palette.setItemText(118, _translate("Dialog", "saddlebrown"))
        self.combo_palette.setItemText(119, _translate("Dialog", "salmon"))
        self.combo_palette.setItemText(120, _translate("Dialog", "sandybrown"))
        self.combo_palette.setItemText(121, _translate("Dialog", "seagreen"))
        self.combo_palette.setItemText(122, _translate("Dialog", "seashell"))
        self.combo_palette.setItemText(123, _translate("Dialog", "sienna"))
        self.combo_palette.setItemText(124, _translate("Dialog", "silver"))
        self.combo_palette.setItemText(125, _translate("Dialog", "skyblue"))
        self.combo_palette.setItemText(126, _translate("Dialog", "slateblue"))
        self.combo_palette.setItemText(127, _translate("Dialog", "slategray"))
        self.combo_palette.setItemText(128, _translate("Dialog", "snow"))
        self.combo_palette.setItemText(129, _translate("Dialog", "springgreen"))
        self.combo_palette.setItemText(130, _translate("Dialog", "steelblue"))
        self.combo_palette.setItemText(131, _translate("Dialog", "tan"))
        self.combo_palette.setItemText(132, _translate("Dialog", "teal"))
        self.combo_palette.setItemText(133, _translate("Dialog", "thistle"))
        self.combo_palette.setItemText(134, _translate("Dialog", "tomato"))
        self.combo_palette.setItemText(135, _translate("Dialog", "turquoise"))
        self.combo_palette.setItemText(136, _translate("Dialog", "violet"))
        self.combo_palette.setItemText(137, _translate("Dialog", "wheat"))
        self.combo_palette.setItemText(138, _translate("Dialog", "white"))
        self.combo_palette.setItemText(139, _translate("Dialog", "whitesmoke"))
        self.combo_palette.setItemText(140, _translate("Dialog", "yellow"))
        self.combo_palette.setItemText(141, _translate("Dialog", "yellowgreen"))
        self.label_15.setText(_translate("Dialog", "This setting requires a restart to take effect."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Appearance"))
        self.check_valid_load.setText(_translate("Dialog", "Validate installer."))
        self.check_valid_load_ignore.setText(_translate("Dialog", "Ignore errors and continue loading."))
        self.check_warn_load.setText(_translate("Dialog", "Check installer for common errors."))
        self.check_warn_load_ignore.setText(_translate("Dialog", "Ignore errors and continue loading."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Loading"))
        self.check_valid_save.setText(_translate("Dialog", "Validate installer."))
        self.check_valid_save_ignore.setText(_translate("Dialog", "Ignore errors and continue saving."))
        self.check_warn_save.setText(_translate("Dialog", "Check installer for common errors."))
        self.check_warn_save_ignore.setText(_translate("Dialog", "Ignore errors and continue saving."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Saving"))
        self.label_4.setText(_translate("Dialog", "Node Name"))
        self.label_3.setText(_translate("Dialog", "Property Name"))
        self.label_5.setText(_translate("Dialog", "Default Value"))
        self.check_installSteps.setText(_translate("Dialog", "Installation Steps"))
        self.label_2.setText(_translate("Dialog", "Order"))
        self.combo_installSteps.setItemText(0, _translate("Dialog", "Explicit"))
        self.combo_installSteps.setItemText(1, _translate("Dialog", "Ascending"))
        self.combo_installSteps.setItemText(2, _translate("Dialog", "Descending"))
        self.check_optionalFileGroups.setText(_translate("Dialog", "Option Group"))
        self.label_6.setText(_translate("Dialog", "Order"))
        self.combo_optionalFileGroups.setItemText(0, _translate("Dialog", "Explicit"))
        self.combo_optionalFileGroups.setItemText(1, _translate("Dialog", "Ascending"))
        self.combo_optionalFileGroups.setItemText(2, _translate("Dialog", "Descending"))
        self.check_type.setText(_translate("Dialog", "Type"))
        self.label_7.setText(_translate("Dialog", "Type"))
        self.combo_type.setItemText(0, _translate("Dialog", "Optional"))
        self.combo_type.setItemText(1, _translate("Dialog", "Required"))
        self.combo_type.setItemText(2, _translate("Dialog", "Recommended"))
        self.combo_type.setItemText(3, _translate("Dialog", "CouldBeUsable"))
        self.combo_type.setItemText(4, _translate("Dialog", "NotUsable"))
        self.check_defaultType.setText(_translate("Dialog", "Default Type"))
        self.label_8.setText(_translate("Dialog", "Type"))
        self.combo_defaultType.setItemText(0, _translate("Dialog", "Optional"))
        self.combo_defaultType.setItemText(1, _translate("Dialog", "Required"))
        self.combo_defaultType.setItemText(2, _translate("Dialog", "Recommended"))
        self.combo_defaultType.setItemText(3, _translate("Dialog", "CouldBeUsable"))
        self.combo_defaultType.setItemText(4, _translate("Dialog", "NotUsable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Defaults"))

