# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/templates/wizard_plugin_01.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 563)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(Form)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.imageLabel = QtWidgets.QLabel(Form)
        self.imageLabel.setObjectName("imageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.imageLabel)
        self.imageWidget = QtWidgets.QWidget(Form)
        self.imageWidget.setObjectName("imageWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imageWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_image = QtWidgets.QLineEdit(self.imageWidget)
        self.edit_image.setObjectName("edit_image")
        self.horizontalLayout_3.addWidget(self.edit_image)
        self.button_image = QtWidgets.QPushButton(self.imageWidget)
        self.button_image.setMinimumSize(QtCore.QSize(30, 20))
        self.button_image.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_image.setBaseSize(QtCore.QSize(0, 0))
        self.button_image.setObjectName("button_image")
        self.horizontalLayout_3.addWidget(self.button_image)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.imageWidget)
        self.descriptionLabel = QtWidgets.QLabel(Form)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionLineEdit = QtWidgets.QLineEdit(Form)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_files = QtWidgets.QPushButton(Form)
        self.button_files.setObjectName("button_files")
        self.verticalLayout.addWidget(self.button_files)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.button_flag = QtWidgets.QPushButton(Form)
        self.button_flag.setObjectName("button_flag")
        self.verticalLayout.addWidget(self.button_flag)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 435, 73))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layout_flag = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.layout_flag.setContentsMargins(0, 0, 0, 0)
        self.layout_flag.setObjectName("layout_flag")
        spacerItem = QtWidgets.QSpacerItem(20, 155, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_flag.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_type = QtWidgets.QRadioButton(Form)
        self.radio_type.setCheckable(True)
        self.radio_type.setChecked(True)
        self.radio_type.setObjectName("radio_type")
        self.horizontalLayout_2.addWidget(self.radio_type)
        self.combo_type = QtWidgets.QComboBox(Form)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_type)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radio_depend = QtWidgets.QRadioButton(Form)
        self.radio_depend.setObjectName("radio_depend")
        self.horizontalLayout_4.addWidget(self.radio_depend)
        self.button_depend = QtWidgets.QPushButton(Form)
        self.button_depend.setEnabled(False)
        self.button_depend.setObjectName("button_depend")
        self.horizontalLayout_4.addWidget(self.button_depend)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.finish_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finish_button.sizePolicy().hasHeightForWidth())
        self.finish_button.setSizePolicy(sizePolicy)
        self.finish_button.setObjectName("finish_button")
        self.horizontalLayout.addWidget(self.finish_button)
        self.cancel_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Plugin Wizard"))
        self.label.setText(_translate("Form", "<html><head/><body><p>TODO</p><p>See the <span style=\" text-decoration: underline;\">Help</span> for more information.</p></body></html>"))
        self.nameLabel.setText(_translate("Form", "Name"))
        self.imageLabel.setText(_translate("Form", "Image"))
        self.button_image.setText(_translate("Form", "..."))
        self.descriptionLabel.setText(_translate("Form", "Description"))
        self.button_files.setText(_translate("Form", "Manage Files To Install"))
        self.label_2.setText(_translate("Form", "Flags To Be Set:"))
        self.button_flag.setText(_translate("Form", "Add Flag"))
        self.label_3.setText(_translate("Form", "Plugin Type:"))
        self.radio_type.setText(_translate("Form", "Type:"))
        self.combo_type.setItemText(0, _translate("Form", "Required"))
        self.combo_type.setItemText(1, _translate("Form", "Optional"))
        self.combo_type.setItemText(2, _translate("Form", "Recommended"))
        self.radio_depend.setText(_translate("Form", "Dependent Type:"))
        self.button_depend.setText(_translate("Form", "Manage Type Dependencies"))
        self.finish_button.setText(_translate("Form", "Finish"))
        self.cancel_button.setText(_translate("Form", "Cancel"))

